name: validate

on:
  # Manually triggered
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "info"
        type: choice
        options:
          - debug
          - info
          - warn
          - error
  # Trigger the workflow on push or pull request
  push:
    branches:
      - main
      - next
    paths-ignore:
      - '**/.gitignore'
      - '**/.eslintrc.js'
      - '**/README.md'
      - '**/LICENSE'
      - '**/.prettierrc.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node: [ 14, 16 ]

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        # run: echo "::set-output name=dir::$(yarn cache dir)" // yarn v1
        # run: echo "::set-output name=dir::$(yarn config get cacheFolder)" // yarn v2+ -- this is now deprecated from GitHub
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Restore cache
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install modules
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn --immutable

      - name: Validate
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
               yarn validate
          elif [ "$RUNNER_OS" == "Windows" ]; then
               yarn test
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi
        shell: bash
